#!/usr/bin/env python
import sys
import numpy as np
import pickle
from core.network import Network
from core.utils import zero_padding
from core.kernel_ops import *
from core.postprocess_ops import *

def build():
  autopolls = Network()
  autopolls.add_op(Input())
  autopolls.add_op(Quantize())
  autopolls.connect_ops(-1, 0)
  autopolls.add_op(Conv2D(stride=2))
  autopolls.connect_ops(0, 1)
  autopolls.add_op(DepthwiseConv2D())
  autopolls.connect_ops(1, 2)
  autopolls.add_op(Conv2D())
  autopolls.connect_ops(2, 3)
  autopolls.add_op(Conv2D())
  autopolls.connect_ops(3, 4)
  autopolls.add_op(DepthwiseConv2D(stride=2))
  autopolls.connect_ops(4, 5)
  autopolls.add_op(Conv2D())
  autopolls.connect_ops(5, 6)
  autopolls.add_op(Conv2D())
  autopolls.connect_ops(6, 7)
  autopolls.add_op(DepthwiseConv2D())
  autopolls.connect_ops(7, 8)
  autopolls.add_op(Conv2D())
  autopolls.connect_ops(8, 9)
  autopolls.add_op(Add())
  autopolls.connect_ops(9, 10)
  autopolls.connect_ops(6, 10)
  autopolls.add_op(Conv2D())
  autopolls.connect_ops(10, 11)
  autopolls.add_op(DepthwiseConv2D(stride=2))
  autopolls.connect_ops(11, 12)
  autopolls.add_op(Conv2D())
  autopolls.connect_ops(12, 13)
  autopolls.add_op(Conv2D())
  autopolls.connect_ops(13, 14)
  autopolls.add_op(DepthwiseConv2D())
  autopolls.connect_ops(14, 15)
  autopolls.add_op(Conv2D())
  autopolls.connect_ops(15, 16)
  autopolls.add_op(Add())
  autopolls.connect_ops(16, 17)
  autopolls.connect_ops(13, 17)
  autopolls.add_op(Conv2D())
  autopolls.connect_ops(17, 18)
  autopolls.add_op(DepthwiseConv2D())
  autopolls.connect_ops(18, 19)
  autopolls.add_op(Conv2D())
  autopolls.connect_ops(19, 20)
  autopolls.add_op(Add())
  autopolls.connect_ops(20, 21)
  autopolls.connect_ops(17, 21)
  autopolls.add_op(Conv2D())
  autopolls.connect_ops(21, 22)
  autopolls.add_op(Conv2D())
  autopolls.connect_ops(21, 23)
  autopolls.add_op(DepthwiseConv2D(stride=2))
  autopolls.connect_ops(23, 24)
  autopolls.add_op(Conv2D())
  autopolls.connect_ops(24, 25)
  autopolls.add_op(Conv2D())
  autopolls.connect_ops(25, 26)
  autopolls.add_op(DepthwiseConv2D())
  autopolls.connect_ops(26, 27)
  autopolls.add_op(Conv2D())
  autopolls.connect_ops(27, 28)
  autopolls.add_op(Add())
  autopolls.connect_ops(28, 29)
  autopolls.connect_ops(25, 29)
  autopolls.add_op(Conv2D())
  autopolls.connect_ops(29, 30)
  autopolls.add_op(DepthwiseConv2D())
  autopolls.connect_ops(30, 31)
  autopolls.add_op(Conv2D())
  autopolls.connect_ops(31, 32)
  autopolls.add_op(Add())
  autopolls.connect_ops(32, 33)
  autopolls.connect_ops(29, 33)
  autopolls.add_op(Conv2D())
  autopolls.connect_ops(33, 34)
  autopolls.add_op(DepthwiseConv2D())
  autopolls.connect_ops(34, 35)
  autopolls.add_op(Conv2D())
  autopolls.connect_ops(35, 36)
  autopolls.add_op(Add())
  autopolls.connect_ops(36, 37)
  autopolls.connect_ops(33, 37)
  autopolls.add_op(Conv2D())
  autopolls.connect_ops(37, 38)
  autopolls.add_op(DepthwiseConv2D())
  autopolls.connect_ops(38, 39)
  autopolls.add_op(Conv2D())
  autopolls.connect_ops(39, 40)
  autopolls.add_op(Conv2D())
  autopolls.connect_ops(40, 41)
  autopolls.add_op(DepthwiseConv2D())
  autopolls.connect_ops(41, 42)
  autopolls.add_op(Conv2D())
  autopolls.connect_ops(42, 43)
  autopolls.add_op(Add())
  autopolls.connect_ops(43, 44)
  autopolls.connect_ops(40, 44)
  autopolls.add_op(Conv2D())
  autopolls.connect_ops(44, 45)
  autopolls.add_op(DepthwiseConv2D())
  autopolls.connect_ops(45, 46)
  autopolls.add_op(Conv2D())
  autopolls.connect_ops(46, 47)
  autopolls.add_op(Add())
  autopolls.connect_ops(47, 48)
  autopolls.connect_ops(44, 48)
  autopolls.add_op(Conv2D())
  autopolls.connect_ops(48, 49)
  autopolls.add_op(Conv2D())
  autopolls.connect_ops(48, 50)
  autopolls.add_op(DepthwiseConv2D(stride=2))
  autopolls.connect_ops(50, 51)
  autopolls.add_op(Conv2D())
  autopolls.connect_ops(51, 52)
  autopolls.add_op(Conv2D())
  autopolls.connect_ops(52, 53)
  autopolls.add_op(DepthwiseConv2D())
  autopolls.connect_ops(53, 54)
  autopolls.add_op(Conv2D())
  autopolls.connect_ops(54, 55)
  autopolls.add_op(Add())
  autopolls.connect_ops(55, 56)
  autopolls.connect_ops(52, 56)
  autopolls.add_op(Conv2D())
  autopolls.connect_ops(56, 57)
  autopolls.add_op(DepthwiseConv2D())
  autopolls.connect_ops(57, 58)
  autopolls.add_op(Conv2D())
  autopolls.connect_ops(58, 59)
  autopolls.add_op(Add())
  autopolls.connect_ops(59, 60)
  autopolls.connect_ops(56, 60)
  autopolls.add_op(Conv2D())
  autopolls.connect_ops(60, 61)
  autopolls.add_op(DepthwiseConv2D())
  autopolls.connect_ops(61, 62)
  autopolls.add_op(Conv2D())
  autopolls.connect_ops(62, 63)
  autopolls.add_op(Conv2D())
  autopolls.connect_ops(63, 64)
  autopolls.add_op(Conv2D())
  autopolls.connect_ops(64, 65)
  autopolls.add_op(Pack(axis=3, count=2))
  autopolls.connect_ops(65, 66)
  autopolls.add_op(Reshape())
  autopolls.connect_ops(66, 67)
  autopolls.add_op(Pack(axis=2, count=2))
  autopolls.connect_ops(67, 68)
  autopolls.add_op(Reshape())
  autopolls.connect_ops(68, 69)
  autopolls.add_op(Add())
  autopolls.connect_ops(69, 70)
  autopolls.connect_ops(49, 70)
  autopolls.add_op(DepthwiseConv2D())
  autopolls.connect_ops(70, 71)
  autopolls.add_op(Conv2D())
  autopolls.connect_ops(71, 72)
  autopolls.add_op(Pack(axis=3, count=2))
  autopolls.connect_ops(72, 73)
  autopolls.add_op(Reshape())
  autopolls.connect_ops(73, 74)
  autopolls.add_op(Pack(axis=2, count=2))
  autopolls.connect_ops(74, 75)
  autopolls.add_op(Reshape())
  autopolls.connect_ops(75, 76)
  autopolls.add_op(Add())
  autopolls.connect_ops(76, 77)
  autopolls.connect_ops(22, 77)
  autopolls.add_op(DepthwiseConv2D())
  autopolls.connect_ops(77, 78)
  autopolls.add_op(Conv2D())
  autopolls.connect_ops(78, 79)
  autopolls.add_op(DepthwiseConv2D(stride=2))
  autopolls.connect_ops(65, 80)
  autopolls.add_op(Conv2D())
  autopolls.connect_ops(80, 81)
  autopolls.add_op(DepthwiseConv2D(stride=2))
  autopolls.connect_ops(81, 82)
  autopolls.add_op(Conv2D())
  autopolls.connect_ops(82, 83)
  autopolls.add_op(DepthwiseConv2D())
  autopolls.connect_ops(79, 84)
  autopolls.add_op(Conv2D())
  autopolls.connect_ops(84, 85)
  autopolls.add_op(DepthwiseConv2D())
  autopolls.connect_ops(72, 86)
  autopolls.add_op(Conv2D())
  autopolls.connect_ops(86, 87)
  autopolls.add_op(DepthwiseConv2D())
  autopolls.connect_ops(65, 88)
  autopolls.add_op(Conv2D())
  autopolls.connect_ops(88, 89)
  autopolls.add_op(DepthwiseConv2D())
  autopolls.connect_ops(81, 90)
  autopolls.add_op(Conv2D())
  autopolls.connect_ops(90, 91)
  autopolls.add_op(DepthwiseConv2D())
  autopolls.connect_ops(83, 92)
  autopolls.add_op(Conv2D())
  autopolls.connect_ops(92, 93)
  autopolls.add_op(DepthwiseConv2D())
  autopolls.connect_ops(85, 94)
  autopolls.add_op(Conv2D())
  autopolls.connect_ops(94, 95)
  autopolls.add_op(DepthwiseConv2D())
  autopolls.connect_ops(87, 96)
  autopolls.add_op(Conv2D())
  autopolls.connect_ops(96, 97)
  autopolls.add_op(DepthwiseConv2D())
  autopolls.connect_ops(89, 98)
  autopolls.add_op(Conv2D())
  autopolls.connect_ops(98, 99)
  autopolls.add_op(DepthwiseConv2D())
  autopolls.connect_ops(91, 100)
  autopolls.add_op(Conv2D())
  autopolls.connect_ops(100, 101)
  autopolls.add_op(DepthwiseConv2D())
  autopolls.connect_ops(93, 102)
  autopolls.add_op(Conv2D())
  autopolls.connect_ops(102, 103)
  autopolls.add_op(DepthwiseConv2D())
  autopolls.connect_ops(95, 104)
  autopolls.add_op(Conv2D())
  autopolls.connect_ops(104, 105)
  autopolls.add_op(DepthwiseConv2D())
  autopolls.connect_ops(97, 106)
  autopolls.add_op(Conv2D())
  autopolls.connect_ops(106, 107)
  autopolls.add_op(DepthwiseConv2D())
  autopolls.connect_ops(99, 108)
  autopolls.add_op(Conv2D())
  autopolls.connect_ops(108, 109)
  autopolls.add_op(DepthwiseConv2D())
  autopolls.connect_ops(101, 110)
  autopolls.add_op(Conv2D())
  autopolls.connect_ops(110, 111)
  autopolls.add_op(DepthwiseConv2D())
  autopolls.connect_ops(103, 112)
  autopolls.add_op(Conv2D())
  autopolls.connect_ops(112, 113)
  autopolls.add_op(DepthwiseConv2D())
  autopolls.connect_ops(105, 114)
  autopolls.add_op(Conv2D())
  autopolls.connect_ops(114, 115)
  autopolls.add_op(DepthwiseConv2D())
  autopolls.connect_ops(107, 116)
  autopolls.add_op(Conv2D())
  autopolls.connect_ops(116, 117)
  autopolls.add_op(DepthwiseConv2D())
  autopolls.connect_ops(109, 118)
  autopolls.add_op(Conv2D())
  autopolls.connect_ops(118, 119)
  autopolls.add_op(DepthwiseConv2D())
  autopolls.connect_ops(111, 120)
  autopolls.add_op(Conv2D())
  autopolls.connect_ops(120, 121)
  autopolls.add_op(DepthwiseConv2D())
  autopolls.connect_ops(113, 122)
  autopolls.add_op(Conv2D())
  autopolls.connect_ops(122, 123)
  autopolls.add_op(DepthwiseConv2D())
  autopolls.connect_ops(115, 124)
  autopolls.add_op(Conv2D())
  autopolls.connect_ops(124, 125)
  autopolls.add_op(Reshape())
  autopolls.connect_ops(125, 126)
  autopolls.add_op(DepthwiseConv2D())
  autopolls.connect_ops(117, 127)
  autopolls.add_op(Conv2D())
  autopolls.connect_ops(127, 128)
  autopolls.add_op(Reshape())
  autopolls.connect_ops(128, 129)
  autopolls.add_op(DepthwiseConv2D())
  autopolls.connect_ops(119, 130)
  autopolls.add_op(Conv2D())
  autopolls.connect_ops(130, 131)
  autopolls.add_op(Reshape())
  autopolls.connect_ops(131, 132)
  autopolls.add_op(DepthwiseConv2D())
  autopolls.connect_ops(121, 133)
  autopolls.add_op(Conv2D())
  autopolls.connect_ops(133, 134)
  autopolls.add_op(Reshape())
  autopolls.connect_ops(134, 135)
  autopolls.add_op(DepthwiseConv2D())
  autopolls.connect_ops(123, 136)
  autopolls.add_op(Conv2D())
  autopolls.connect_ops(136, 137)
  autopolls.add_op(Reshape())
  autopolls.connect_ops(137, 138)
  autopolls.add_op(Concatenation(axis=1))
  autopolls.connect_ops(126, 139)
  autopolls.connect_ops(129, 139)
  autopolls.connect_ops(132, 139)
  autopolls.connect_ops(135, 139)
  autopolls.connect_ops(138, 139)
  autopolls.add_op(Dequantize())
  autopolls.connect_ops(139, 140)
  
  autopolls.add_op(DepthwiseConv2D())
  autopolls.connect_ops(115, 141)
  autopolls.add_op(Conv2D())
  autopolls.connect_ops(141, 142)
  autopolls.add_op(Reshape())
  autopolls.connect_ops(142, 143)

  autopolls.add_op(DepthwiseConv2D())
  autopolls.connect_ops(117, 144)
  autopolls.add_op(Conv2D())
  autopolls.connect_ops(144, 145)
  autopolls.add_op(Reshape())
  autopolls.connect_ops(145, 146)

  autopolls.add_op(DepthwiseConv2D())
  autopolls.connect_ops(119, 147)
  autopolls.add_op(Conv2D())
  autopolls.connect_ops(147, 148)
  autopolls.add_op(Reshape())
  autopolls.connect_ops(148, 149)

  autopolls.add_op(DepthwiseConv2D())
  autopolls.connect_ops(121, 150)
  autopolls.add_op(Conv2D())
  autopolls.connect_ops(150, 151)
  autopolls.add_op(Reshape())
  autopolls.connect_ops(151, 152)

  autopolls.add_op(DepthwiseConv2D())
  autopolls.connect_ops(123, 153)
  autopolls.add_op(Conv2D())
  autopolls.connect_ops(153, 154)
  autopolls.add_op(Reshape())
  autopolls.connect_ops(154, 155)

  autopolls.add_op(Concatenation(axis=1))
  autopolls.connect_ops(143, 156)
  autopolls.connect_ops(146, 156)
  autopolls.connect_ops(149, 156)
  autopolls.connect_ops(152, 156)
  autopolls.connect_ops(155, 156)
  autopolls.add_op(Logistic())
  autopolls.connect_ops(156, 157)
  autopolls.add_op(Dequantize())
  autopolls.connect_ops(157, 158)

if __name__=="__main__":
  np.set_printoptions(threshold=sys.maxsize)
  # TODO: Add code to load an image from the autopolls image dataset

  model = build()